version: '3.9'

services:

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ../mosquitto:/mosquitto/config

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: energy
      POSTGRES_PASSWORD: energy123
      POSTGRES_DB: energydb
    ports:
      - "5432:5432"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
